// Centralized domain constants (BP-CONST-001 — no magic numbers in logic).
// Values that model Naano's real published mechanics are grouped and sourced.

export const SITE = {
  name: "Naano",
  tagline: "The B2B LinkedIn Creator Marketplace",
  description:
    "Find the creators your buyers already trust, launch campaigns in days, and track the clicks, leads and pipeline generated by every post.",
} as const;

// Homepage social-proof stats (mirrors the live marketing copy).
export const MARKETPLACE_STATS = {
  creators: "3,000+",
  countries: "100",
  impressions: "5M+",
  leads: "30K+",
  audienceMatch: "96%",
} as const;

// --- ICP taxonomy: shared across creator audience data + campaign targeting ---
export const AUDIENCE_FUNCTIONS = [
  "Founders",
  "Marketing",
  "Sales/BD",
  "Engineering/Data",
  "Product",
  "Finance/VC",
  "HR/People",
  "Operations",
] as const;

export const AUDIENCE_SENIORITIES = [
  "Founder/C-level",
  "VP/Head/Director",
  "Manager/Lead",
  "Senior IC",
] as const;

export const VERTICALS = [
  "B2B SaaS",
  "Fintech",
  "DevTools",
  "AI/ML",
  "Sales/Marketing",
  "HR/Future-of-work",
  "E-commerce",
  "Cybersecurity",
  "Data/Analytics",
] as const;

export type AudienceFunction = (typeof AUDIENCE_FUNCTIONS)[number];
export type AudienceSeniority = (typeof AUDIENCE_SENIORITIES)[number];
export type Vertical = (typeof VERTICALS)[number];

// --- Fit-score algorithm weights (deterministic ICP match, 0..100) ---
export const FIT_SCORE_WEIGHTS = {
  functionMatch: 0.45,
  seniorityMatch: 0.35,
  verticalMatch: 0.2,
  // Floor so an on-topic creator never shows an alarmingly low score.
  floor: 35,
} as const;

// --- Creator "worth" calculator (from Naano's published model) ---
export const CREATOR_WORTH = {
  euroPer1kFollowers: 12,
  floorPrice: 100,
  engagementBase: 0.6,
  engagementDivisor: 2.5,
  engagementCapMultiplier: 2,
  roundingStep: 10,
  nicheMultipliers: {
    "B2B SaaS": 1.2,
    DevTools: 1.2,
    "AI/ML": 1.2,
    Fintech: 1.15,
    "Sales/Marketing": 1.1,
    "HR/Future-of-work": 1.0,
    default: 0.9,
  } as Record<string, number>,
} as const;

// --- Sponsored-post delivery odds by price band (Naano Q2-2026 benchmarks) ---
export const DELIVERY_RATES = [
  { label: "Under €200", maxPrice: 200, rate: 0.304 },
  { label: "€200–€400", maxPrice: 400, rate: 0.45 },
  { label: "€400–€600", maxPrice: 600, rate: 0.56 },
  { label: "Over €600", maxPrice: Infinity, rate: 0.646 },
] as const;

// Median per-post price by follower band (used for budget planning + seeding).
export const PRICE_BANDS = [
  { label: "< 5K", maxFollowers: 5000, median: 84 },
  { label: "5–10K", maxFollowers: 10000, median: 180 },
  { label: "10–25K", maxFollowers: 25000, median: 312 },
  { label: "25–50K", maxFollowers: 50000, median: 480 },
  { label: "50K+", maxFollowers: Infinity, median: 720 },
] as const;

export const MIN_POST_PRICE = 20;
export const MAX_POST_PRICE = 5000;

// --- Pricing tiers ---
export const PRICING_PLANS = [
  {
    id: "SELF_SERVE",
    name: "Self-Serve",
    price: "€0",
    cadence: "/mo",
    blurb: "No retainer, no minimum spend. Month-to-month.",
    cta: "Start for free",
    featured: false,
    features: [
      "Creator marketplace access",
      "AI-powered brief creation",
      "Track clicks, companies & pipeline",
      "Automatic creator payouts",
      "Fixed price per post — from €20",
    ],
  },
  {
    id: "MANAGED",
    name: "Managed Campaigns",
    price: "€700",
    cadence: "/mo",
    blurb: "Done-for-you by the Naano team.",
    cta: "Book a campaign call",
    featured: true,
    features: [
      "Everything in Self-Serve",
      "Campaign strategy & positioning",
      "Creator sourcing & coordination",
      "Brief creation & launch",
      "Reporting & optimisation",
    ],
  },
] as const;

// --- Pagination defaults (BP-PAGINATION-001) ---
export const PAGE_SIZE_DEFAULT = 24;
export const PAGE_SIZE_MAX = 100;

// --- Auth hardening (OWASP-AUTH-001 / RATELIMIT-001) ---
export const BCRYPT_ROUNDS = 12;
export const MAX_FAILED_LOGIN_ATTEMPTS_BEFORE_LOCKOUT = 5;
export const ACCOUNT_LOCKOUT_DURATION_MS = 15 * 60 * 1000; // 15 minutes

// --- AI brief generation limits ---
export const AI_BRIEF_PROMPT_MAX_CHARS = 2000;
export const AI_BRIEF_TIMEOUT_MS = 30_000;

// Booking pipeline order (drives the campaign kanban board).
export const BOOKING_PIPELINE = [
  "INVITED",
  "ACCEPTED",
  "DRAFT_SUBMITTED",
  "APPROVED",
  "SCHEDULED",
  "LIVE",
  "PAID",
] as const;
