import type { Metadata } from "next";
import {
  Search,
  FileText,
  KanbanSquare,
  BarChart3,
  Wallet,
  Sparkles,
  ArrowRight,
} from "lucide-react";
import { SiteNav } from "@/components/marketing/site-nav";
import { SiteFooter } from "@/components/marketing/site-footer";
import { Hero } from "@/components/marketing/hero";
import { LogoCloud } from "@/components/marketing/logo-cloud";
import { FeatureSteps } from "@/components/marketing/feature-steps";
import { StatStrip } from "@/components/marketing/stat-strip";
import { Testimonial } from "@/components/marketing/testimonial";
import { PricingCards } from "@/components/marketing/pricing-cards";
import { Faq } from "@/components/marketing/faq";
import { CtaBand } from "@/components/marketing/cta-band";
import { ButtonLink } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { MARKETPLACE_STATS } from "@/lib/constants";

export const metadata: Metadata = {
  title: "Naano — The B2B LinkedIn Creator Marketplace",
  description:
    "Find the creators your buyers already trust, launch campaigns in days, and track the clicks, leads and pipeline generated by every post.",
};

const HOME_STEPS = [
  {
    title: "Find creators your buyers trust",
    description:
      "Search by vertical and ICP, not vanity follower counts. Naano surfaces vetted creators whose audience is actually made of your buyers.",
    icon: <Search className="size-5" />,
  },
  {
    title: "Build a campaign brief in minutes",
    description:
      "Describe your product and objective. Our AI drafts the angle, hook, key messages and do/don't list — you just refine and approve.",
    icon: <FileText className="size-5" />,
  },
  {
    title: "Manage every collaboration",
    description:
      "Invite creators, review drafts and schedule posts from one board. Track each booking from draft to live at a glance.",
    icon: <KanbanSquare className="size-5" />,
    visual: (
      <div className="flex flex-wrap gap-2">
        <Badge variant="default">Draft</Badge>
        <Badge variant="warning">Scheduled</Badge>
        <Badge variant="success">Live</Badge>
      </div>
    ),
  },
  {
    title: "Track reach, clicks, and leads",
    description:
      "Every post carries tracked links, so you see impressions, clicks per creator and the leads and pipeline each collaboration generates.",
    icon: <BarChart3 className="size-5" />,
  },
  {
    title: "Pay creators without the admin",
    description:
      "Fixed price per post, agreed up front. Naano handles invoicing and payouts so you never chase a contract or a transfer again.",
    icon: <Wallet className="size-5" />,
  },
];

const HOME_STATS = [
  { value: MARKETPLACE_STATS.impressions, label: "Impressions generated" },
  { value: MARKETPLACE_STATS.leads, label: "Leads captured" },
  { value: MARKETPLACE_STATS.creators, label: "Vetted B2B creators" },
  { value: MARKETPLACE_STATS.audienceMatch, label: "Average audience match" },
];

const HOME_FAQ = [
  {
    question: "What is Naano?",
    answer:
      "Naano is a B2B LinkedIn creator marketplace. It connects companies with vetted creators whose audiences are made of their buyers, then helps them brief, launch, track and pay for sponsored posts — all in one place.",
  },
  {
    question: "How much does it cost?",
    answer:
      "The Self-Serve plan is free — you only pay creators a fixed price per post, starting from €20. There are no per-click, per-impression or per-lead fees. A €700/mo Managed plan adds a done-for-you campaign team.",
  },
  {
    question: "How does tracking work?",
    answer:
      "Every collaboration gets a unique tracked link. When someone clicks through from a creator's post, Naano records the click and attributes any resulting leads and pipeline back to that creator and post.",
  },
  {
    question: "How are creators vetted?",
    answer:
      "We review each creator's audience composition — function, seniority and vertical — not just their follower count, so you book people who genuinely reach decision-makers in your market.",
  },
  {
    question: "Do posts come from the creator's own account?",
    answer:
      "Yes. Posts go live from creators' personal profiles, where LinkedIn concentrates organic reach, and are written in their own authentic voice after you approve the draft.",
  },
  {
    question: "Can agencies use Naano?",
    answer:
      "Absolutely. Brand agencies get a workspace per client to run campaigns, and creator agencies can import and manage a full roster of creators from a single login.",
  },
];

export default function HomePage() {
  return (
    <>
      <SiteNav transparent />

      <Hero
        tone="dark"
        badge={
          <>
            <Sparkles className="size-3.5" />
            Where B2B brands work with creators
          </>
        }
        title={
          <>
            The B2B LinkedIn{" "}
            <span className="text-gradient">Creator Marketplace.</span>
          </>
        }
        subtitle="Find the creators your buyers already trust, launch campaigns in days, and track the clicks, leads and pipeline generated by every post."
        actions={
          <>
            <ButtonLink href="/register?role=company" variant="white" size="lg">
              Launch a campaign
              <ArrowRight className="size-4" />
            </ButtonLink>
            <ButtonLink
              href="/how-it-works"
              variant="ghost"
              size="lg"
              className="text-white hover:bg-white/10"
            >
              See how Naano works
            </ButtonLink>
          </>
        }
        footnote="Trusted by modern B2B teams"
      >
        <LogoCloud tone="dark" label="" />
      </Hero>

      <FeatureSteps
        eyebrow="How it works"
        heading="One platform, from brief to results"
        subheading="Everything you need to run creator campaigns that your finance team can actually measure."
        steps={HOME_STEPS}
        numbered
      />

      <StatStrip stats={HOME_STATS} tone="dark" />

      <Testimonial
        eyebrow="Case study"
        heading="Real teams. Measurable pipeline."
        quote="Naano became one of our fastest acquisition channels. We know exactly what every creator brings."
        authorName="Vincent Josse"
        authorRole="CEO, BlogSEO"
        caseLabel="BlogSEO campaign"
        caseStats={[
          { value: "€5,000", label: "Campaign budget" },
          { value: "~20", label: "Sponsored posts" },
          { value: "1,500+", label: "Qualified leads" },
          { value: "150%", label: "ROAS" },
        ]}
      />

      <PricingCards />

      <Faq
        heading="Everything you wanted to know"
        subheading="Still curious? These are the questions B2B teams ask us most."
        items={HOME_FAQ}
      />

      <CtaBand
        title="Ready to scale with naano?"
        subtitle="Launch your first creator campaign in days — or let our team run it for you."
        actions={
          <>
            <ButtonLink href="/register?role=company" variant="white" size="lg">
              Launch a campaign
              <ArrowRight className="size-4" />
            </ButtonLink>
            <ButtonLink
              href="/pricing"
              variant="ghost"
              size="lg"
              className="text-white hover:bg-white/10"
            >
              Book a campaign call
            </ButtonLink>
          </>
        }
      />

      <SiteFooter />
    </>
  );
}
