// Pure, constants-driven calculation helpers for the Free Tools calculators.
// Business logic is isolated here (BP-FUNC-001) and every number comes from
// @/lib/constants (BP-CONST-001). All functions are defensive against empty /
// zero / NaN input (BP-NULL-001) and return a discriminated result so the UI
// can render a dash instead of "NaN" or "Infinity".

import {
  CREATOR_WORTH,
  DELIVERY_RATES,
  PRICE_BANDS,
} from "@/lib/constants";

// Assumptions surfaced to the user as clearly-labelled estimates.
export const BUDGET_ASSUMPTIONS = {
  // Rough average impressions generated by a single published sponsored post.
  impressionsPerPost: 15_000,
  // Share of impressions that convert to a lead — kept as a low/high range.
  leadRateLow: 0.01,
  leadRateHigh: 0.03,
} as const;

// A comment is weighted as a stronger engagement signal than a reaction.
const COMMENT_WEIGHT = 2;

/** True only for a real, finite, positive number. */
function isPositiveFinite(value: number): boolean {
  return Number.isFinite(value) && value > 0;
}

/**
 * Weighted engagement rate as a *fraction* (0.042 = 4.2%).
 * Returns null when followers is not a positive number, so callers never
 * divide by zero or surface NaN.
 */
export function engagementRateFraction(
  followers: number,
  avgReactions: number,
  avgComments: number,
): number | null {
  if (!isPositiveFinite(followers)) return null;
  const reactions = Number.isFinite(avgReactions) ? Math.max(avgReactions, 0) : 0;
  const comments = Number.isFinite(avgComments) ? Math.max(avgComments, 0) : 0;
  return (reactions + COMMENT_WEIGHT * comments) / followers;
}

export type EngagementQuality = "low" | "solid" | "excellent";

/** Qualitative band for an engagement rate given as a percentage value. */
export function engagementQuality(ratePercent: number): EngagementQuality {
  if (ratePercent < 1) return "low";
  if (ratePercent <= 3) return "solid";
  return "excellent";
}

export type CreatorWorthResult = {
  engagementRatePercent: number;
  base: number;
  engagementMultiplier: number;
  engagementAdjusted: number;
  nicheMultiplier: number;
  suggestedPrice: number;
  rangeLow: number;
  rangeHigh: number;
};

// ±20% suggested-price band shown alongside the point estimate.
const PRICE_RANGE_SPREAD = 0.2;

/**
 * Naano's creator "worth" model. Returns null when followers is invalid so the
 * UI shows a dash rather than a nonsensical price.
 */
export function computeCreatorWorth(
  followers: number,
  avgReactions: number,
  avgComments: number,
  niche: string,
): CreatorWorthResult | null {
  const erFraction = engagementRateFraction(followers, avgReactions, avgComments);
  if (erFraction === null) return null;

  const engagementRatePercent = erFraction * 100;

  const base = Math.max(
    (CREATOR_WORTH.euroPer1kFollowers * followers) / 1000,
    CREATOR_WORTH.floorPrice,
  );

  // engagementRate is used here as a percent value, per the model spec, and the
  // resulting multiplier is capped so a viral outlier can't inflate the price.
  const engagementMultiplier = Math.min(
    CREATOR_WORTH.engagementBase +
      engagementRatePercent / CREATOR_WORTH.engagementDivisor,
    CREATOR_WORTH.engagementCapMultiplier,
  );

  const engagementAdjusted = base * engagementMultiplier;

  const nicheMultiplier =
    CREATOR_WORTH.nicheMultipliers[niche] ??
    CREATOR_WORTH.nicheMultipliers.default;

  const raw = engagementAdjusted * nicheMultiplier;

  const rounded =
    Math.round(raw / CREATOR_WORTH.roundingStep) * CREATOR_WORTH.roundingStep;
  const suggestedPrice = Math.max(rounded, CREATOR_WORTH.floorPrice);

  return {
    engagementRatePercent,
    base,
    engagementMultiplier,
    engagementAdjusted,
    nicheMultiplier,
    suggestedPrice,
    rangeLow: Math.round(suggestedPrice * (1 - PRICE_RANGE_SPREAD)),
    rangeHigh: Math.round(suggestedPrice * (1 + PRICE_RANGE_SPREAD)),
  };
}

export type DeliveryBand = (typeof DELIVERY_RATES)[number];

/** The delivery-rate band a given per-post price falls into (null if invalid). */
export function deliveryBandForPrice(price: number): DeliveryBand | null {
  if (!isPositiveFinite(price)) return null;
  return DELIVERY_RATES.find((band) => price <= band.maxPrice) ?? null;
}

export type PriceBand = (typeof PRICE_BANDS)[number];

/** Look up a follower price band by its label. */
export function priceBandByLabel(label: string): PriceBand | undefined {
  return PRICE_BANDS.find((band) => band.label === label);
}

export type BudgetPlan = {
  medianPrice: number;
  deliveryRate: number;
  bookedPosts: number;
  publishedPosts: number;
  totalImpressions: number;
  leadsLow: number;
  leadsHigh: number;
};

/**
 * Campaign budget plan: how many published posts a budget buys at a given
 * per-post price, plus a rough leads estimate. Returns null for invalid inputs.
 */
export function computeBudgetPlan(
  budget: number,
  pricePerPost: number,
): BudgetPlan | null {
  if (!isPositiveFinite(budget) || !isPositiveFinite(pricePerPost)) return null;

  const band = deliveryBandForPrice(pricePerPost);
  if (band === null) return null;

  const bookedPosts = budget / pricePerPost;
  const publishedPosts = bookedPosts * band.rate;
  const totalImpressions = publishedPosts * BUDGET_ASSUMPTIONS.impressionsPerPost;

  return {
    medianPrice: pricePerPost,
    deliveryRate: band.rate,
    bookedPosts,
    publishedPosts,
    totalImpressions,
    leadsLow: totalImpressions * BUDGET_ASSUMPTIONS.leadRateLow,
    leadsHigh: totalImpressions * BUDGET_ASSUMPTIONS.leadRateHigh,
  };
}
